#!/usr/bin/env bash
#
set -e
#
cd /var/www || exit 1
#

npm install --production --omit=dev --prefer-offline --no-audit --progress=false
npm install laravel-mix@latest
npm install --save-dev vite laravel-vite-plugin
npm run build
composer update --no-interaction --prefer-dist --optimize-autoloader --no-dev --no-progress --no-plugins --no-scripts --no-ansi
composer dump-autoload -o
php artisan key:generate --no-interaction --force
php artisan migrate:fresh --seed --no-interaction --force
php artisan optimize:clear
php artisan storage:link
php artisan horizon:publish




#exec "$@"
